import { motion } from "framer-motion";
import { FileText, Download, Loader2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import jsPDF from "jspdf";
import AppLayout from "@/components/layout/AppLayout";
import RiskBadge from "@/components/dashboard/RiskBadge";
import { fetchEntities, type DbEntity } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import type { RiskLevel } from "@/data/mockData";

function formatCurrency(amount: number) {
  if (!amount) return "₹0";
  if (amount >= 10000000) return `₹${(amount / 10000000).toFixed(2)} Cr`;
  if (amount >= 100000) return `₹${(amount / 100000).toFixed(2)} L`;
  return `₹${amount.toLocaleString()}`;
}

function generatePDF(entity: DbEntity) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(20, 20, 30);
  doc.rect(0, 0, w, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("CORRUPTION INVESTIGATION REPORT", w / 2, 18, { align: "center" });
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()} | CONFIDENTIAL`, w / 2, 30, { align: "center" });
  y = 50;

  doc.setTextColor(0, 0, 0);

  // Subject
  doc.setFontSize(14);
  doc.text(`Subject: ${entity.name}`, 15, y);
  y += 10;
  doc.setFontSize(10);
  doc.text(`Type: ${entity.type} | Department: ${entity.department || "N/A"} | Location: ${entity.location}`, 15, y);
  y += 7;
  doc.text(`Designation: ${entity.designation || "N/A"}`, 15, y);
  y += 12;

  // Risk Assessment
  doc.setFontSize(12);
  doc.setTextColor(200, 0, 0);
  doc.text("RISK ASSESSMENT", 15, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Risk Score: ${entity.risk_score}/100 (${entity.risk_level?.toUpperCase()})`, 15, y); y += 6;
  doc.text(`AI Prediction Score: ${entity.prediction_score}/100`, 15, y); y += 6;
  doc.text(`Complaints: ${entity.complaints_count} | Contracts: ${entity.contracts_count} | News Hits: ${entity.news_hits}`, 15, y); y += 6;
  doc.text(`Political Connections: ${entity.political_connections} | Dark Web Signals: ${entity.dark_web_signals} | Financial Anomalies: ${entity.financial_anomalies}`, 15, y);
  y += 12;

  // Financial Profile
  doc.setFontSize(12);
  doc.setTextColor(200, 0, 0);
  doc.text("FINANCIAL PROFILE", 15, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Declared Income: ${formatCurrency(entity.declared_income)}`, 15, y); y += 6;
  doc.text(`Known Spending: ${formatCurrency(entity.known_spending)}`, 15, y); y += 6;
  doc.text(`Known Assets: ${formatCurrency(entity.known_assets)}`, 15, y); y += 6;
  doc.text(`Income-Spending Ratio: ${entity.income_spending_ratio}x`, 15, y); y += 6;
  doc.text(`Wealth Source: ${entity.wealth_source || "Unknown"}`, 15, y); y += 6;
  doc.text(`Disproportionate Wealth: ${entity.disproportionate_wealth ? "YES — FLAGGED" : "No"}`, 15, y);
  y += 12;

  // Wealth Gap Analysis
  const wealthGap = (entity.known_spending + entity.known_assets) - entity.declared_income;
  if (wealthGap > 0) {
    doc.setFontSize(12);
    doc.setTextColor(200, 0, 0);
    doc.text("WEALTH GAP ANALYSIS", 15, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Unexplained Wealth Gap: ${formatCurrency(wealthGap)}`, 15, y); y += 6;
    doc.text(`Spending exceeds declared income by ${entity.income_spending_ratio}x`, 15, y);
    y += 12;
  }

  // Bio
  if (entity.bio) {
    doc.setFontSize(12);
    doc.setTextColor(200, 0, 0);
    doc.text("PROFILE SUMMARY", 15, y);
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    const bioLines = doc.splitTextToSize(entity.bio, w - 30);
    doc.text(bioLines, 15, y);
    y += bioLines.length * 5 + 10;
  }

  // Footer
  if (y > 260) { doc.addPage(); y = 20; }
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("This report is auto-generated by the Anti-Corruption Intelligence Platform. For official use only.", w / 2, 285, { align: "center" });

  doc.save(`Investigation_Report_${entity.name.replace(/\s+/g, "_")}.pdf`);
}

export default function ReportsPage() {
  const { data: entities } = useQuery({ queryKey: ["entities-reports"], queryFn: () => fetchEntities() });

  const reports = (entities || []).filter((e) => e.risk_score >= 40).map((e) => ({
    ...e,
    sections: ["Profile Summary", "Contract Analysis", "Complaint History", "Network Relationships", "AI Prediction", "Evidence Summary"],
  }));

  return (
    <AppLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold">Investigation Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">Auto-generated corruption investigation reports</p>
        </div>

        <div className="space-y-3 max-w-4xl">
          {reports.map((report, i) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.03 }}
              className="glass-panel-hover p-5 flex items-center gap-4"
            >
              <div className="p-2.5 rounded-lg bg-primary/10 shrink-0">
                <FileText className="w-5 h-5 text-primary" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold">Investigation Report: {report.name}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{report.department} • {report.location} • Score: {report.risk_score}/100</p>
                <div className="flex gap-1.5 mt-2 flex-wrap">
                  {report.sections.slice(0, 3).map((s) => (
                    <span key={s} className="px-2 py-0.5 rounded-full bg-secondary text-[10px] text-muted-foreground">{s}</span>
                  ))}
                  <span className="text-[10px] text-muted-foreground">+{report.sections.length - 3} more</span>
                </div>
              </div>
              <div className="flex items-center gap-3 shrink-0">
                <RiskBadge level={report.risk_level as RiskLevel} />
                <Button size="sm" variant="outline" onClick={() => toast.info("PDF generation available with full backend integration")} className="text-xs border-border/50 text-foreground hover:bg-secondary">
                  <Download className="w-3.5 h-3.5 mr-1.5" /> PDF
                </Button>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </AppLayout>
  );
}
